apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ip-sentry.fullname" . }}-enforcer-script
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ip-sentry.labels" . | nindent 4 }}
data:
  enforcer.sh: |
{{ tpl (.Files.Get "files/enforcer.sh") . | indent 4 }}
